services:
  db:
    image: postgres:16-alpine
    container_name: cenimatch-db
    environment:
      POSTGRES_USER: u
      POSTGRES_PASSWORD: "112233"
      POSTGRES_DB: cenimatch-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
